### ISSUE TITLE
automate webhook registration and improve policy choice

### ISSUE THREAD

**Issue by davidkarlsen** [anchore/anchore-charts#10]
https://github.com/anchore/anchore-charts/blob/master/stable/anchore-admission-controller/files/get_validating_webhook_config.sh seems to contain some manual steps for registering the webhook. This should be documented in the README.md

Additionally could this simply be templated and handled by helm alongside the rest of the chart?

Further I think it makes sense to set the [failurePolicy](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy) to `Ignore` in order to avoid the control-plane malfunctioning if the controller should start failing.

**Comment by davidkarlsen** [comment]
I did a search for `ValidatingWebhookConfiguration` -  https://github.com/helm/charts/search?q=ValidatingWebhookConfiguration - maybe pick up some inspiration from there?

**Comment by zhill** [comment]
I'd like to ensure we support the namespace selector, so that can be added in the values.yaml and automated in deploy as well.
