### ISSUE TITLE
Fixup Permissions in Scratch Directory when using AWS EFS Storage

### ISSUE THREAD

**Issue by adawalli** [anchore/anchore-charts#100]
When using AWS' EFS storage through the k8s CSI driver, the volume is mounted and owned by `root:root` in the deployed pods. 

k8s does allow enforcement of group ownership through their [fsGroup](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod) parameter.

Unfortunately, as documented by [here](https://github.com/kubernetes/examples/issues/260), [here](https://stackoverflow.com/questions/46769339/how-to-change-permission-of-mapped-volume-in-kubernetes-docker), and [here](https://docs.aws.amazon.com/efs/latest/ug/accessing-fs-nfs-permissions.html), NFS permissions do not get corrected properly by **fsGroup**

As documented in those threads, this problem can be resolved with some **initContainer** magic. I will submit a PR to address this.

**Comment by Btodhunter** [comment]
fixed with pr #101
