### ISSUE TITLE
Add helm/charts/stable/anchore-engine to this repository

### ISSUE THREAD

**Issue by Btodhunter** [anchore/anchore-charts#15]
Our official stable/anchore-engine chart will need to be migrated to this chart repository in preparation for the helm2 deprecation.

The `stable` chart repository will be deprecated to security only fixes on May 13, 2020 and completely removed on November 13, 2020.

**Comment by sc250024** [comment]
Nice!

**Comment by Btodhunter** [comment]
To make the switch to a new chart repository easy & to allow users on older version of k8s to utilize the chart, we will directly migrate the stable chart to a legacy version.

I suggest we add the chart using this structure:
anchore-charts/legacy/anchore-engine
