### ISSUE TITLE
Chart install times out when using helm install --repo reference

### ISSUE THREAD

**Issue by agentreno** [anchore/anchore-charts#2]
Hi, I'm having some issues installing the admission controller. The helm install hangs, the debug output doesn't say much but if I manual inspect with kubectl, I see:

```
# kubectl describe job admission-init-ca
...
Events:
  Type     Reason        Age                   From            Message
  ----     ------        ----                  ----            -------
  Warning  FailedCreate  119s (x5 over 4m29s)  job-controller  Error creating: Internal error occurred: failed calling admission webhook "admission-anchore-admission-controller.admission.anchore.io": the server could not find the requested resource

# kubectl describe ValidatingWebhookConfiguration admission-anchore-admission-controller.admission.anchore.io

Name:         admission-anchore-admission-controller.admission.anchore.io
Namespace:
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"ValidatingWebhookConfiguration","metadata":{"annotations":{},"name":"admissio...
API Version:  admissionregistration.k8s.io/v1beta1
Kind:         ValidatingWebhookConfiguration
Metadata:
  Creation Timestamp:  2019-02-03T14:39:49Z
  Generation:          1
  Resource Version:    623778
  Self Link:           /apis/admissionregistration.k8s.io/v1beta1/validatingwebhookconfigurations/admission-anchore-admission-controller.admission.anchore.io
  UID:                 8f5a7ff6-27c1-11e9-a425-0a002ac40f5c
Webhooks:
  Client Config:
    Ca Bundle:  <redacted>
    Service:
      Name:        kubernetes
      Namespace:   default
      Path:        /apis/admission.anchore.io/v1beta1/imagechecks
  Failure Policy:  Fail
  Name:            admission-anchore-admission-controller.admission.anchore.io
  Namespace Selector:
  Rules:
    API Groups:

    API Versions:
      *
    Operations:
      CREATE
    Resources:
      pods
Events:  <none>
```

It's worth mentioning there's been a few reinstalls of the chart at this point, and it was working initially, but I'm seeing this after running helm delete --purge and running the cleanup script.

As a side note, it might be that the ValidatingWebhookConfiguration object also needs adding to the cleanup script.

**NOTE** tested again referencing the chart from a local git clone and didn't encounter this problem - does charts.anchore.io need updating?

**Comment by zhill** [comment]
@agentreno there are some issues with the cleanup process and things left over from the init-ca jobs. I'm working to make the ca/cert process much cleaner but as it stands now, there are some things left behind.

Before a re-install you'll need to delete the validating webhook configurations otherwise it will block deployment of new pods. I didn't add this to the cleanup script because it may not be strictly required if you setup the namespace selector on the validating webhook configuration to exclude the namespace that the controller runs in.

**Comment by agentreno** [comment]
Got it, I think this can be closed, I've been able to successfully install using the --repo reference provided the ValidatingWebhookConfiguration is removed, thereby allowing helm install to create pods.

Like you said, it's probably advisable to put the controller in another namespace and change the config so it doesn't block itself.

**Comment by zhill** [comment]
closing, per last comment. can look into updates in the readme/install instructions to help clarify
