### ISSUE TITLE
anchoreEnterpriseRbac.annotations missing in values file 

### ISSUE THREAD

**Issue by gaevans-ebay** [anchore/anchore-charts#209]
It appears that the anchoreEnterpriseRbac block in the values.yaml is missing annotations but it is referenced in the template.

**Comment by gaevans-ebay** [comment]
It is also missing anchoreEnterpriseRbac.labels

**Comment by d3vdr3y** [comment]
Hi @gaevans-ebay thanks for submitting an issue on this. The current `values.yaml` does allow for input of custom labels and annotations in the `anchoreEnterpriseRbac` block. Let me know if you are seeing issues with this rendering during deployment of the chart.

https://github.com/anchore/anchore-charts/blob/main/stable/anchore-engine/values.yaml#L911
https://github.com/anchore/anchore-charts/blob/main/stable/anchore-engine/values.yaml#L912
