### ISSUE TITLE
[anchore-engine] Alter upgrade process for Anchore deployments to use either hooks or init containers

### ISSUE THREAD

**Issue by zhill** [anchore/anchore-charts#23]
Relevant once the chart has migrated to this repo from `stable`.

Anchore upgrades itself, including db schema updates, but those can take time, so a separate, non-service bound, entity in the deployment should handle the upgrade. Could use upgrade hooks, jobs, or init-containers to accomplish this, but the requirements for the process are:

* All engine services must be down prior to upgrade operation
* During db upgrade no services are started
* On successful upgrade, the services are started
* On a failed upgrade, the upgrade can be retried but rollback will require a restore of old db version manually (not part of the chart most likely). Upgrade failures can leave the db in an intermediate stage, and a full upgrade operation must be successfully completed prior to system startup.

**Comment by frittentheke** [comment]
@zhill  thanks for looking into this and making updates a lot more comfortable!

Check out what / how Gitlab does it with their init container `dependencies` which has the newly updated pods (from helm upgrade) wait / block their main containers startup until things are in order.
(i.e. here in the unicorn deployment: https://gitlab.com/gitlab-org/charts/gitlab/-/blob/master/charts/gitlab/charts/unicorn/templates/deployment.yaml#L92.

That container is just a script (https://gitlab.com/gitlab-org/build/CNG/blob/a9b07eef/gitlab-rails/scripts/wait-for-deps) which waits / fails.

Additionally they use a K8S Job that does the (db) migrations (https://gitlab.com/gitlab-org/charts/gitlab/-/tree/master/charts/gitlab/charts/migrations). This Job is just always deployed when a helm chart update happens

**Comment by Btodhunter** [comment]
This functionality was added to a post-upgrade helm hook job in chart version 1.6.4
