### ISSUE TITLE
Create a stable/engine chart that only installs the OSS components

### ISSUE THREAD

**Issue by Btodhunter** [anchore/anchore-charts#28]
The stable/engine chart should only install the open source components of anchore-engine. All enterprise related components will be removed from the chart to reduce complexity.

**Comment by robertp** [comment]
Yesterday and today (in the fork https://github.com/robertp/anchore-charts) I added anchore-engine and enterprise chart directories, pulled enterprise-specific things out of the anchore-engine chart, and with Brady's help refactored global configuration/configmap stuff into a separate template.  WIP, needs review.

This newly organized 'enterprise free' chart does install locally with kind, and images add and scan.

**Comment by robertp** [comment]
@Btodhunter I think this is ready for you to review and determine next steps. I'm guessing that the README and comments in the values file will need some attention, and I could use some guidance on that.

**Comment by Btodhunter** [comment]
closing as stale
