### ISSUE TITLE
Chart missing affinity and tolerations

### ISSUE THREAD

**Issue by antimack** [anchore/anchore-charts#4]
Hi. According to `values.yaml` file there should be affinity and tolerations, but they are missing in the deployment template, can you guys please add them?

**Comment by antimack** [comment]
Will actually controller work with 2 replicas, won't be any race conditions or collisions? If yes, I can create a PR for adding affinity and tolerations. The idea is since users will depend on Admission controller and pods won't schedule depending on policy/gate rules it's good to have at least 2 replicas and schedule them with anti-affinity so at least they won't be on the same node.

**Comment by zhill** [comment]
@antimack thanks for filing the issue. It should support those properties. As for replication, yes it should work as there is no in-memory state or other state between requests that could cause conflict or collisions.

**Comment by antimack** [comment]
thanks for your reply! yep, it should support, but in the templates/anchore-admission-controller.yaml
there is only NodeSelector:
```
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
  {{- end }}
``` 
so even if I will add affinity to the values.yaml file it won't be reflected

also, not related question, when I will create ValidatingWebhookConfiguration will it check and validate pods in all the namespaces by default? I have added selector for the specific namespace in to the:
policySelectors:
  - Selector: ...  
but that is probably related to the Anchore scans?
how doest it work? I am afraid to block all the pods in the big dev cluster :)

**Comment by zhill** [comment]
Correct, by "should" I meant "is intended to". There is clearly an issue.

Re: selector and namespace: you can configure the controller to do passive analysis request to start so that you can watch the logs and get a feel for it before setting the config to a more aggressive mode. I can also confirm that the namespace selector in the validating webhook configuration object does work and can be used to include/exclude namespaces from validation checks.

**Comment by antimack** [comment]
ok, I see, so just to summarise:
with namespace selector in the validating webhook configuration object we can control what will be validated with admission controller, then we can also control with selector in controller configuration what resource types level(image, pod, namespace) we will use to evaluate/gate against specified policy, but if selectors are not specified will it check and evaluate everything?

also, it's a little bit confusing with "passive analysis" is it equal to "breakglass" ?
  "Strict Policy-Based Admission Gating Mode" == "policy"? -> pods won't be scheduled before image submitted and analyzed and we will receive "PASS" (will controller submit images for analyzing before?  or images **should** be analyzed manually/with CI before?) and what will be with pods, they will be in "ContainerCreting"/"Pending"
  "Analysis-Based Admission Gating Mode" == "analyze"? -> controller will submit images for analyzing, and will wait for them to be analyzed but won't evaluate against policy?
  "Passive Analysis Trigger Mode" == "breakglass" ->  controller will submit images for analyzing but won't do anything

thanks for explanation in advance, I think you do a really great stuff!

**Comment by zhill** [comment]
Yes, that should work. You can use whatever label you want you just have to make them match in the Validating  Webhook Configuration object, there isn't any magic in that particular name, just an example.

**Comment by zhill** [comment]
> ok, I see, so just to summarise:
> with namespace selector in the validating webhook configuration object we can control what will be validated with admission controller, then we can also control with selector in controller configuration what resource types level(image, pod, namespace) we will use to evaluate/gate against specified policy, but if selectors are not specified will it check and evaluate everything?

Yes that is correct.

> 
> also, it's a little bit confusing with "passive analysis" is it equal to "breakglass" ?
> "Strict Policy-Based Admission Gating Mode" == "policy"? -> pods won't be scheduled before image submitted and analyzed and we will receive "PASS" (will controller submit images for analyzing before? or images **should** be analyzed manually/with CI before?) and what will be with pods, they will be in "ContainerCraeting"/"Pending"
> "Analysis-Based Admission Gating Mode" == "analysis"? -> controller will submit images for analyzing, and will wait for them to be analyzed but won't evaluate against policy?
> "Passive Analysis Trigger Mode" == "breakglass" -> controller will submit images for analyzing but won't do anything

Break glass short-circuits everything, or should. It looks like it falls-thru to request analysis if that is set. That is a bug. It should skip the analysis request in that case. I'll file another issue for that and fix it.

> > I can also confirm that the namespace selector in the validating webhook configuration object does work and can be used to include/exclude namespaces from validation checks.
> 
> so to simply exclude a namespace I just need to uncomment that part and add label `exclude.admission.anchore.io=true` to a namespace?
> 
> thanks for explanation in advance, I think you do a really great stuff!

Thanks, and you're very welcome! Trying to balance flexibility with usability here, and feedback is very much appreciated!
