### ISSUE TITLE
Cannot install admission controller using helm3

### ISSUE THREAD

**Issue by riponbanik** [anchore/anchore-charts#43]
When running  helm3 -n anchore install anchore-democtl -f ctl_values.yaml . it shows the following error -

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ValidatingWebhookConfiguration): unknown field "labels" in io.k8s.api.admissionregistration.v1beta1.ValidatingWebhookConfiguration

**Comment by riponbanik** [comment]
Have made a pull request - https://github.com/anchore/anchore-charts/pull/44

**Comment by robertp** [comment]
Hi @riponbanik thank you for your PR! I verified your change, and also verified it against the metadata label syntax reference (https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/).

Please add a DCO (https://probot.github.io/apps/dco/), for example by amending your commit (git commit --amend -s) (see https://github.com/anchore/anchore-charts/pull/44/checks?check_run_id=802089284 for details).

Cheers,
Robert

**Comment by robertp** [comment]
Hello @riponbanik - I haven't seen your DCO come in yet, so I'm going to submit your fix from a different fork. Thank you!

**Comment by riponbanik** [comment]
@robertp  Thanks. I have signed off and pushed.

**Comment by zhill** [comment]
Is this resolved?

**Comment by riponbanik** [comment]
@zhill sorry cannot test now. But I could download the chart during that time and with the modification, I could run locally.
