### ISSUE TITLE
Update Controller API version

### ISSUE THREAD

**Issue by d3vdr3y** [anchore/anchore-charts#48]
Receiving the following error when trying to deploy the chart on Helm v3: 

`Error: unable to build kubernetes objects from release manifest: unable to recognize no matches for kind "Deployment" in version "extensions/v1beta1"`

The issue is resolved when the webhook deployment template is updated to **admissionregistration.k8s.io/v1**. This also requires declaring the following in the webhook config: **admissionReviewVersions** and **sideEffects**

**Comment by zhill** [comment]
This is an issue with the k8s version you're deploying to, not helm3 I think. Regardless, the chart needs to be updated with the newer API version.

**Comment by moise3** [comment]
Hi,
any update for this issue ? I have a same problem with helm v3

**Comment by zhill** [comment]
I see the issue. The chart has been updated but not pushed to the index. We'll do some testing and get it published soon. Once you see the 0.2.9 version of the chart or newer, it should be working with the correct API versions.

**Comment by zhill** [comment]
I'll update this issue when the updated repo goes live with the newer version of the chart.

**Comment by Btodhunter** [comment]
The fixed version of the chart is now available on the chart repo. Closing the issue.
