### ISSUE TITLE
Allow specifying database endpoint as an existing secret

### ISSUE THREAD

**Issue by Btodhunter** [anchore/anchore-charts#52]
Right now the ANCHORE_DB_HOST environment variable is specified in the configmap and cannot be overridden with the .Values.anchoreGlobal.existingSecret value

**Comment by flickerfly** [comment]
Really, it'd be nice to have all the database connection information (username, port) in one secret and then specify just that in existingSecret. Also, I'd want to make sure that the .Values.anchoreGlobal.existingSecret implementation also cooresponded to the other uses of existingSecret keys throughout the chart. 

What would be even better is if I could simply mark something like `.Values.anchoreGlobal.existingSecrets: true` and all the charts would assume I'm using a pre-defined named secret. Just make them something like anchore-custom-ui, anchore-custom-feed, anchore-custom-engine, then document that and I'll create those ahead of time. Tracking down all this stuff to implement this securely is driving me to want to give up and take a less secure and easy way.
