### ISSUE TITLE
Missing old chart versions

### ISSUE THREAD

**Issue by pbalogh-sa** [anchore/anchore-charts#56]
Only the latest chart is reachable.
https://hub.helm.sh/charts/anchore/anchore-engine

When you build a new chart the previous one disappears.

https://charts.anchore.io/index.yaml

**Comment by zhill** [comment]
Thanks @pbalogh-sa we're taking a look.

**Comment by Btodhunter** [comment]
Thanks for pointing this out @pbalogh-sa! I fixed the issue in our deployment workflow & updated the index.yaml to include all old releases of the charts. This should no longer be an issue in the future.
