### ISSUE TITLE
SAML secret should be put in kubernetes secret

### ISSUE THREAD

**Issue by BrianKopp** [anchore/anchore-charts#60]
Currently in the `stable/anchore-engine/templates/engine_configmap.yaml`, the saml secret is placed via a hard-coded values.yaml value. This should be able to be placed in a kubernetes secret.

```
    # Locations for keys used for signing and encryption. Only one of 'secret' or 'public_key_path'/'private_key_path' needs to be set. If all are set then the keys take precedence over the secret value
    # Secret is for a shared secret and if set, all components in anchore should have the exact same value in their configs.
    keys:
     >>> secret: {{ .Values.anchoreGlobal.saml.secret }}<<<
      {{- with .Values.anchoreGlobal.saml.publicKeyName }}
      public_key_path: /home/anchore/certs/{{- . }}
      {{- end }}
      {{- with .Values.anchoreGlobal.saml.privateKeyName }}
      private_key_path: /home/anchore/certs/{{- . }}
      {{- end }}
```

**Comment by Btodhunter** [comment]
@BrianKopp Thanks for pointing this out! I'll get an update in asap to store the SAML secret as a k8s secret.

**Comment by adawalli** [comment]
any updates on this @Btodhunter? This is making GITOPs insecure as we essentially have to commit this secret into our values file. Thanks!

**Comment by Btodhunter** [comment]
@BrianKopp Sorry for the delay! I just put in pr #102 to address this. Still working on getting it properly tested, but will merge as soon as I confirm it's working as expected. Give it a once over and let me know if this solution will work for you!
