### ISSUE TITLE
Any reason for the Recreate strategy for all anchore application pods in the helm charts

### ISSUE THREAD

**Issue by sindhams** [anchore/anchore-charts#73]
Hi Team,

I am using anchore helm charts and observed that the application pods have recreate strategy rather than the rolling update strategy . Rolling update strategy is very helpful during the upgrades for less downtime. Just want to know if there is any reason for this.

For example, analyzer pod has recreate strategy in the below file on line number 25.

https://github.com/anchore/anchore-charts/blob/master/stable/anchore-engine/templates/analyzer_deployment.yaml

**Comment by sindhams** [comment]
Got it, thanks @Btodhunter

**Comment by Btodhunter** [comment]
np @sindhams! Closing the issue as resolved.
