### ISSUE TITLE
Anchore Helm Chart for Enterprise UI Ignores "existingSecret" Postgres Password

### ISSUE THREAD

**Issue by blang9238** [anchore/anchore-charts#91]
Throughout nearly all of the Helm Chart for Anchore, the existingSecret is properly respected for pulling secrets. However, in the case of the Enterprise UI, this existing secret is completely ignored for the Postgres Password, and .Values.postgresql.postgresPassword is used (which won't be the right password).

https://github.com/anchore/anchore-charts/blob/master/stable/anchore-engine/templates/enterprise_ui_config_secret.yaml#L55 

Can the UI deployment please read this password from the existing secret instead of insecurely reading only from values?

**Comment by adawalli** [comment]
FWIW, I am still seeing the issue after the two PR - I haven't dug in too deep, but I still have to set .Values.postgresql.postrgresPassword in order for the UI to work
