### ISSUE TITLE
how to load custom policies with helm chart?

### ISSUE THREAD

**Issue by tuananh** [anchore/anchore-charts#99]
is there a volume i can mount or sth like that?

or can i manage it with git?

**Comment by Btodhunter** [comment]
Good question @tuananh! We're actually introducing a mechanism for loading policy bundles at bootstrap with the helm chart in pr #98 - they will be added to `.Values.anchoreGlobal.policyBundles`

**Comment by Btodhunter** [comment]
Fixed with pr #98

**Comment by yusufcemalcelebi** [comment]
Hi, when I passed the custom policy with helm, it creates the ConfigMap and mounts it to the required pods. But when I run this command `anchore-cli policy list` I couldn't see the policy that I passed. So is there a way to pass a policy and using it actively?  Thanks!
